### ISSUE TITLE
todo: 할 일 정리

### ISSUE THREAD

**Issue by jungeun5-choi** [jungeun5-choi/wanted-pre-onboarding-backend#2]
### 기능 요구 사항 (기본)
- [ ] 채용공고 등록
- [ ] 채용공고 수정
- [ ] 채용공고 삭제
- [ ] 채용공고 조회
- [ ] 채용 상세 페이지 조회

### 기능 요구 사항 (가산점)
- [ ] 채용 공고 검색
- [ ] 채용 상세 페이지 조회 시 - 해당 회사의 다른 채용공고 함께 표시
- [ ] 채용공고에 입사지원

### 기능 요구 사항 외
- [ ] 각 기능에 대한 테스트 코드 작성
- [ ] 예외 처리 및 에러 핸들링
- [ ] ![Swagger](https://img.shields.io/badge/-Swagger-%23Clojure?style=for-the-badge&logo=swagger&logoColor=white) 사용?
